"""Generate Venues for EventHub

Uses AWS Bedrock (Claude 3 Haiku) to generate realistic venue data.
Focused on San Francisco Bay Area for realism and interviewer familiarity.

Venue Schema:
    - venue_id: str (e.g., "v_00001") - Generated by Python
    - name: str - Generated by LLM
    - address: str - Generated by LLM (realistic SF Bay Area address)
    - neighborhood: str - Generated by LLM
    - city: str - Generated by LLM (SF, Oakland, San Jose, etc.)
    - capacity: int - Generated by Python
    - category: str - Generated by LLM (music, theater, comedy, art, sports)

Distribution:
    - San Francisco: 20 venues (50%)
    - Oakland/East Bay: 10 venues (25%)
    - San Jose/South Bay: 10 venues (25%)

Usage:
    python generate_venues.py           # Append mode (default)
    python generate_venues.py --rewrite # Clear and regenerate
    python generate_venues.py --test    # Generate 5 venues only
"""

import random
from config import (
    invoke_claude_json_list,
    append_to_jsonl,
    clear_file,
    load_from_jsonl,
    print_progress,
    DATA_COUNTS,
    BATCH_SIZES,
    OUTPUT_FILES,
)


# ============================================
# CONFIGURATION
# ============================================

# Override default counts for venues
VENUE_COUNT = 40  # Total venues
VENUE_BATCH_SIZE = 10  # Venues per LLM call

# Regional distribution
REGIONS = {
    "san_francisco": {
        "count": 20,
        "cities": ["San Francisco"],
        "neighborhoods": [
            "SOMA", "Mission District", "Castro", "Marina", "North Beach",
            "Haight-Ashbury", "Tenderloin", "Civic Center", "Nob Hill",
            "Russian Hill", "Fisherman's Wharf", "Western Addition", "Divisadero"
        ]
    },
    "east_bay": {
        "count": 10,
        "cities": ["Oakland", "Berkeley", "Emeryville"],
        "neighborhoods": [
            "Downtown Oakland", "Jack London Square", "Uptown Oakland",
            "Temescal", "Rockridge", "Downtown Berkeley", "Telegraph Ave"
        ]
    },
    "south_bay": {
        "count": 10,
        "cities": ["San Jose", "Palo Alto", "Mountain View", "Santa Clara"],
        "neighborhoods": [
            "Downtown San Jose", "Santana Row", "Willow Glen",
            "Downtown Palo Alto", "Castro Street", "Santa Clara"
        ]
    }
}

VENUE_CATEGORIES = ["music", "theater", "comedy", "art", "sports", "conference"]


# ============================================
# ID GENERATOR
# ============================================

class IDGenerator:
    """Generates unique sequential IDs."""
    
    def __init__(self, prefix: str = "v"):
        self.prefix = prefix
        self.counter = 0
    
    def next_id(self) -> str:
        self.counter += 1
        return f"{self.prefix}_{self.counter:05d}"
    
    def next_batch(self, count: int) -> list:
        return [self.next_id() for _ in range(count)]


venue_id_generator = IDGenerator(prefix="v")


# ============================================
# PROMPTS
# ============================================

SYSTEM_PROMPT = """You are a data generator for EventHub, an event ticketing platform in the San Francisco Bay Area.
Generate realistic venue data with real-sounding names and addresses.
Use actual neighborhoods and street patterns from the specified cities.
Return ONLY valid JSON array, no additional text."""


def get_venue_prompt(count: int, region: str, cities: list, neighborhoods: list) -> str:
    """Generate prompt for venue creation."""
    return f"""Generate {count} realistic event venues in the {region} as a JSON array.

Location Requirements:
- Cities to use: {', '.join(cities)}
- Neighborhoods to use: {', '.join(neighborhoods)}
- Use realistic street addresses (e.g., "123 Market Street", "456 Broadway")

Each venue should have ONLY these fields:
- name: Creative but realistic venue name (e.g., "The Fillmore", "Great American Music Hall", "Cobb's Comedy Club")
- address: Realistic street address with number
- neighborhood: One of the neighborhoods listed above
- city: One of the cities listed above
- category: One of [music, theater, comedy, art, sports, conference]

Mix of venue types:
- 40% music venues (concert halls, clubs)
- 20% theaters
- 15% comedy clubs
- 15% art galleries/museums
- 10% sports venues or conference centers

Return ONLY the JSON array:
[
  {{"name": "The Grand Theater", "address": "123 Market Street", "neighborhood": "SOMA", "city": "San Francisco", "category": "theater"}},
  ...
]"""


# ============================================
# DATA ENRICHMENT
# ============================================

def generate_capacity(category: str) -> int:
    """Generate realistic capacity based on venue category."""
    capacity_ranges = {
        "music": (200, 3000),
        "theater": (300, 2000),
        "comedy": (100, 500),
        "art": (50, 300),
        "sports": (5000, 20000),
        "conference": (200, 1500),
    }
    min_cap, max_cap = capacity_ranges.get(category, (100, 500))
    return random.randint(min_cap, max_cap)


def enrich_venue(venue: dict, venue_id: str) -> dict:
    """Add Python-generated fields to LLM-generated venue."""
    category = venue.get("category", "music").lower()
    
    return {
        "venue_id": venue_id,
        "name": venue["name"],
        "address": venue["address"],
        "neighborhood": venue["neighborhood"],
        "city": venue["city"],
        "state": "California",
        "capacity": generate_capacity(category),
        "category": category,
    }


# ============================================
# MAIN GENERATION
# ============================================

def generate_venues(rewrite: bool = False):
    """Generate venues for SF Bay Area using Claude 3 Haiku."""
    
    output_file = OUTPUT_FILES["venues"]
    total_venues = VENUE_COUNT
    
    # Handle append vs rewrite mode
    if rewrite:
        print(f"\n🔄 REWRITE MODE: Clearing existing venues")
        clear_file(output_file)
        venue_id_generator.counter = 0
    else:
        if output_file.exists():
            existing = load_from_jsonl(output_file)
            venue_id_generator.counter = len(existing)
            print(f"\n📂 APPEND MODE: Found {len(existing)} existing venues")
        else:
            print(f"\n📂 APPEND MODE: No existing file, starting fresh")
    
    print(f"🚀 Generating {total_venues} venues across SF Bay Area...")
    print(f"   San Francisco: {REGIONS['san_francisco']['count']} venues")
    print(f"   East Bay: {REGIONS['east_bay']['count']} venues")
    print(f"   South Bay: {REGIONS['south_bay']['count']} venues")
    print(f"   Output: {output_file}\n")
    
    generated_count = 0
    
    # Generate venues for each region
    for region_key, region_config in REGIONS.items():
        region_count = region_config["count"]
        cities = region_config["cities"]
        neighborhoods = region_config["neighborhoods"]
        
        region_name = region_key.replace("_", " ").title()
        print(f"\n📍 Generating {region_count} venues for {region_name}...")
        
        # Generate in batches
        region_generated = 0
        while region_generated < region_count:
            batch_size = min(VENUE_BATCH_SIZE, region_count - region_generated)
            
            try:
                prompt = get_venue_prompt(batch_size, region_name, cities, neighborhoods)
                venues_from_llm = invoke_claude_json_list(prompt, SYSTEM_PROMPT)
                
                # Generate unique IDs
                venue_ids = venue_id_generator.next_batch(len(venues_from_llm))
                
                # Enrich venues
                enriched_venues = [
                    enrich_venue(venue, venue_id)
                    for venue, venue_id in zip(venues_from_llm, venue_ids)
                ]
                
                # Save batch
                append_to_jsonl(enriched_venues, output_file)
                
                region_generated += len(enriched_venues)
                generated_count += len(enriched_venues)
                print_progress(generated_count, total_venues, "Venues")
                
            except Exception as e:
                print(f"\n❌ Error generating venues: {e}")
                print("   Retrying...")
                continue
    
    print(f"\n✅ Generated {generated_count} venues to {output_file}")


# ============================================
# ENTRY POINT
# ============================================

if __name__ == "__main__":
    import sys
    
    rewrite_mode = "--rewrite" in sys.argv
    test_mode = "--test" in sys.argv
    
    if test_mode:
        print("🧪 TEST MODE: Generating 5 venues only")
        REGIONS["san_francisco"]["count"] = 2
        REGIONS["east_bay"]["count"] = 2
        REGIONS["south_bay"]["count"] = 1
        VENUE_COUNT = 5  # Module-level variable, no global needed in __main__
    
    if rewrite_mode:
        print("🔄 REWRITE MODE: Will clear existing data")
    else:
        print("📂 APPEND MODE: Will add to existing data (use --rewrite to clear)")
    
    generate_venues(rewrite=rewrite_mode)
