"""Generate Knowledge Base Articles for EventHub

Uses AWS Bedrock (Claude 3 Haiku) to generate help articles for RAG retrieval.
These articles will be used by the agentic system to answer customer questions.

Article Schema:
    - article_id: str (e.g., "kb_00001") - Generated by Python
    - title: str - Generated by LLM
    - content: str - Generated by LLM (detailed help content)
    - category: str - policy/how-to/faq/troubleshooting
    - tags: list - Relevant keywords for search
    - last_updated: str - Article update date

Categories:
    - policy: Refund policy, cancellation policy, terms of service
    - how-to: Step-by-step guides for common tasks
    - faq: Frequently asked questions
    - troubleshooting: Technical issue resolution

Distribution:
    - 100 articles total
    - 25% policy
    - 30% how-to
    - 25% faq
    - 20% troubleshooting

Usage:
    python generate_kb_articles.py           # Append mode (default)
    python generate_kb_articles.py --rewrite # Clear and regenerate
    python generate_kb_articles.py --test    # Generate 10 articles only
"""

import random
from datetime import datetime, timedelta
from config import (
    invoke_claude_json_list,
    append_to_jsonl,
    clear_file,
    load_from_jsonl,
    print_progress,
    OUTPUT_FILES,
)


# ============================================
# CONFIGURATION
# ============================================

ARTICLE_COUNT = 100
ARTICLE_BATCH_SIZE = 10  # Articles per LLM call

# Category configuration
KB_CATEGORIES = {
    "policy": {
        "weight": 0.25,
        "topics": [
            "refund policy for cancelled events",
            "cancellation policy and deadlines",
            "ticket transfer and resale rules",
            "premium membership terms and benefits",
            "privacy policy and data handling",
            "age restrictions and ID requirements",
            "accessibility accommodations policy",
        ]
    },
    "how-to": {
        "weight": 0.30,
        "topics": [
            "how to purchase tickets step by step",
            "how to cancel a reservation",
            "how to request a refund",
            "how to transfer tickets to someone else",
            "how to update account information",
            "how to use mobile tickets and QR codes",
            "how to find and book accessible seating",
            "how to sign up for premium membership",
            "how to use promotional codes and discounts",
            "how to contact customer support",
        ]
    },
    "faq": {
        "weight": 0.25,
        "topics": [
            "what happens if an event is cancelled",
            "can I get a refund after the event",
            "how early should I arrive at the venue",
            "what payment methods are accepted",
            "is there a limit on how many tickets I can buy",
            "can I change my seat after purchasing",
            "what is the difference between premium tiers",
            "how do group discounts work",
        ]
    },
    "troubleshooting": {
        "weight": 0.20,
        "topics": [
            "cannot log into my account",
            "payment declined during checkout",
            "tickets not appearing in my account",
            "QR code not scanning at venue",
            "confirmation email not received",
            "app crashes when opening tickets",
            "browser shows error during purchase",
        ]
    },
}


# ============================================
# ID GENERATOR
# ============================================

class IDGenerator:
    def __init__(self, prefix: str = "kb"):
        self.prefix = prefix
        self.counter = 0
    
    def next_id(self) -> str:
        self.counter += 1
        return f"{self.prefix}_{self.counter:05d}"
    
    def next_batch(self, count: int) -> list:
        return [self.next_id() for _ in range(count)]


article_id_generator = IDGenerator(prefix="kb")


# ============================================
# PROMPTS
# ============================================

SYSTEM_PROMPT = """You are a content writer for EventHub, an event ticketing platform.
Write helpful, clear, and professional knowledge base articles.
Use a friendly but professional tone that's easy for customers to understand.
Include specific steps, examples, and timeframes where relevant.
Return ONLY valid JSON array, no additional text."""


def get_article_prompt(count: int, category: str, topics: list) -> str:
    """Generate prompt for article creation."""
    
    topic_list = random.sample(topics, min(count, len(topics)))
    
    style_guide = {
        "policy": "formal and comprehensive, covering all edge cases and exceptions",
        "how-to": "step-by-step with numbered instructions and tips",
        "faq": "conversational Q&A format with clear answers",
        "troubleshooting": "problem-solution format with multiple resolution steps",
    }
    
    style = style_guide.get(category, "clear and helpful")
    
    return f"""Generate {count} knowledge base articles for the "{category}" category as a JSON array.

Topics to cover (one article per topic):
{chr(10).join(f'- {t}' for t in topic_list)}

Writing style: {style}

Each article should have these fields:
- title: Clear, searchable title (e.g., "How to Request a Refund", "EventHub Cancellation Policy")
- content: Detailed article content (3-5 paragraphs). Include:
    - Overview of the topic
    - Step-by-step instructions or detailed explanation
    - Important notes, exceptions, or tips
    - Contact information or next steps when applicable
- tags: Array of 3-5 relevant keywords for search

Formatting guidelines:
- Use clear paragraph breaks
- Include specific timeframes (e.g., "within 7 business days")
- Mention specific policies (e.g., "24-hour cancellation window")
- Reference the EventHub app and website
- Include realistic but fictional contact details (support@eventhub.com)

Return ONLY the JSON array:
[
  {{
    "title": "How to Request a Refund",
    "content": "If you need to request a refund for your EventHub purchase...",
    "tags": ["refund", "money back", "cancel", "return"]
  }},
  ...
]"""


# ============================================
# DATA ENRICHMENT
# ============================================

def generate_last_updated() -> str:
    """Generate last updated date within past 6 months."""
    today = datetime.now()
    days_ago = random.randint(1, 180)
    update_date = today - timedelta(days=days_ago)
    return update_date.strftime("%Y-%m-%d")


def select_category() -> str:
    """Select article category based on distribution."""
    categories = list(KB_CATEGORIES.keys())
    weights = [KB_CATEGORIES[c]["weight"] for c in categories]
    return random.choices(categories, weights=weights)[0]


def enrich_article(article: dict, article_id: str, category: str) -> dict:
    """Add Python-generated fields to LLM-generated article."""
    
    return {
        "article_id": article_id,
        "title": article["title"],
        "content": article["content"],
        "category": category,
        "tags": article.get("tags", []),
        "last_updated": generate_last_updated(),
        "is_published": True,
        "view_count": random.randint(50, 5000),
        "helpful_votes": random.randint(10, 500),
    }


# ============================================
# MAIN GENERATION
# ============================================

def generate_kb_articles(rewrite: bool = False, test_mode: bool = False):
    """Generate knowledge base articles using Claude 3 Haiku."""
    
    output_file = OUTPUT_FILES["kb_articles"]
    
    # Handle append vs rewrite mode
    if rewrite:
        print(f"\n🔄 REWRITE MODE: Clearing existing articles")
        clear_file(output_file)
        article_id_generator.counter = 0
    else:
        if output_file.exists():
            existing = load_from_jsonl(output_file)
            article_id_generator.counter = len(existing)
            print(f"\n📂 APPEND MODE: Found {len(existing)} existing articles")
    
    total_articles = 10 if test_mode else ARTICLE_COUNT
    print(f"\n🚀 Generating {total_articles} knowledge base articles...")
    print(f"   Output: {output_file}\n")
    
    generated_count = 0
    used_topics = set()  # Avoid duplicate topics
    
    while generated_count < total_articles:
        category = select_category()
        category_config = KB_CATEGORIES[category]
        
        # Get unused topics
        available_topics = [t for t in category_config["topics"] if t not in used_topics]
        if not available_topics:
            # Reset if we've used all topics (for larger datasets)
            available_topics = category_config["topics"]
        
        batch_size = min(ARTICLE_BATCH_SIZE, total_articles - generated_count, len(available_topics))
        
        try:
            prompt = get_article_prompt(batch_size, category, available_topics)
            articles_from_llm = invoke_claude_json_list(prompt, SYSTEM_PROMPT)
            
            # Generate unique IDs
            article_ids = article_id_generator.next_batch(len(articles_from_llm))
            
            # Track used topics
            for topic in available_topics[:len(articles_from_llm)]:
                used_topics.add(topic)
            
            # Enrich articles
            enriched_articles = [
                enrich_article(article, article_id, category)
                for article, article_id in zip(articles_from_llm, article_ids)
            ]
            
            # Save batch
            append_to_jsonl(enriched_articles, output_file)
            
            generated_count += len(enriched_articles)
            print_progress(generated_count, total_articles, "Articles")
            
        except Exception as e:
            print(f"\n❌ Error generating articles: {e}")
            print("   Retrying...")
            continue
    
    print(f"\n✅ Generated {generated_count} knowledge base articles to {output_file}")


# ============================================
# ENTRY POINT
# ============================================

if __name__ == "__main__":
    import sys
    
    rewrite_mode = "--rewrite" in sys.argv
    test_mode = "--test" in sys.argv
    
    if test_mode:
        print("🧪 TEST MODE: Generating 10 articles only")
    
    if rewrite_mode:
        print("🔄 REWRITE MODE: Will clear existing data")
    else:
        print("📂 APPEND MODE: Will add to existing data (use --rewrite to clear)")
    
    generate_kb_articles(rewrite=rewrite_mode, test_mode=test_mode)
